name: game-comment-backend
version: 0.0.1
github: "tasuki/game-comment"

dependencies:
    - base >= 4.7 && < 5
    - scotty
    - aeson
    - bytestring
    - directory
    - dotenv
    - filepath
    - http-client
    - http-client-tls
    - http-types
    - memory
    - scrypt
    - sqlite-simple
    - text
    - time

library:
    source-dirs: src

executables:
    gc-server:
        main: server.hs
        source-dirs: app
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies: game-comment-backend
    gc-migrate:
        main: migrate.hs
        source-dirs: app
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies: game-comment-backend
