name: game-comment-backend
version: 0.0.1
github: "tasuki/game-comment"

dependencies:
    - base >= 4.7 && < 5
    - scotty
    - aeson
    - bytestring
    - http-client
    - http-client-tls
    - http-types
    - memory
    - scrypt
    - sqlite-simple
    - text

executables:
    game-comment-backend:
        main: Main.hs
        source-dirs: .
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
