name: game-comment-backend
version: 0.0.1
github: "tasuki/game-comment"

dependencies:
    - base >= 4.7 && < 5
    - scotty
    - http-client
    - http-client-tls

executables:
    game-comment-backend:
        main: Main.hs
        source-dirs: app
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - bytestring
